config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users
   resources :questions do 
      resources :answers
   end
   root 'questions#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  has_many  :comments, as: :commentable, dependent: :destroy
  validates :body, presence: true, length: { maximum: 1400 }
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  mount_uploader :file, FileUploader
  belongs_to :question
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
  validates :body, presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  # include Votable
  # include Attachable
  
  has_many :answers, dependent: :destroy
  has_many  :comments, as: :commentable, dependent: :destroy
  has_many :attachments #, as: :attachable 
  # has_many :subscribe_lists, dependent: :destroy
  # has_many :subscribers, class_name: 'User', through: :subscribe_lists
  # belongs_to :user

  validates :title, presence: true, length: { maximum: 140 }
  validates :body, presence: true, length: { maximum: 1400 }
  # validates :user, presence: true

  accepts_nested_attributes_for :attachments #, reject_if: proc { |attrib| attrib['file'].nil? }, allow_destroy: true

  # scope :created_yesterday, -> { where(created_at: Time.zone.now.yesterday.all_day) }

  # after_create :subscribe_author

  # self.per_page = 10

  # def subscribe(user)
  #   self.subscribers << user unless has_subscribed? user
  # end

  # def unsubscribe(user)
  #   self.subscribers.delete(user) if has_subscribed? user
  # end

  # def has_subscribed?(user)
  #   subscribers.include? user
  # end

  # private

  # def subscribe_author
  #   subscribe(user)
  # end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :load_answer, only: [:edit, :update, :destroy, :make_best, :render_answer, :render_error, :show]
  before_action :load_question, only: [:create, :make_best, :update]

  def create
    @answer = @question.answers.create(answer_params)
    #redirect_to question_path(@answer.question)
  end

  def update
    @answer.update answer_params
  end
  private

  def load_question
    @question = if params.key?(:question_id)
                  Question.find(params[:question_id])
    else
      @answer.question
    end
  end

  def load_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    answer_params = params.require(:answer).permit(:body, :user_id, attachments_attributes: [:id, :file, :_destroy])
    #answer_params.merge(user_id: current_user.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
   
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :load_question, only: [:show, :edit, :update, :destroy, :subscribe, :unsubscribe]
  before_action :authenticate_user!, only: [:new, :create]
  before_action :build_answer, only: :show
  # # before_action :check_user, only: :destroy
  # after_action  :publish_question, only: :create

  #authorize_resource

  # respond_to :js, only: :update

  # include PublicIndex
  # include Voted

  def index
    @questions =  Question.all
    # respond_with(@questions = Question.all)
    #respond_with(@questions = Question.paginate(page: params[:page]).order('created_at DESC'))
  end

  def show
    #respond_with(@question)
  end

  def new
    @question = Question.new

    @question.attachments.build
    #respond_with(@question = Question.new)
  end

  def edit
  end

  def create
    @question = Question.new question_params
    if @question.save 
      redirect_to @question
    else render :new
    end
    #respond_with(@question = current_user.questions.create(question_params))
  end

  def update
    if @question.update(question_params)
      redirect_to @question
    else render :edit 
    end

    #respond_with @question
  end

  def destroy
     
    @question.destroy
    redirect_to questions_path
    #@respond_with(@question.destroy)
  end

  def subscribe
    @question.subscribe(current_user)
    redirect_to @question, notice: 'Subscribed successfully!'
  end

  def unsubscribe
    @question.unsubscribe(current_user)
    redirect_to @question, notice: 'Unsubscribed successfully!'
  end

  private

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:id, :file, :_destroy])
  end

  def load_question
    @question = Question.find(params[:id])
  end

  def build_answer
    @answer = @question.answers.build
  end

  # def check_user
  #   render text: 'You do not have permission to view this page.', status: 403 if @question.user_id != current_user.id
  # end

  def publish_question
    PrivatePub.publish_to("/questions", question: @question.to_json(include: :attachments)) if @question.valid?
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/answers/_answer.html.slim
- if answer.persisted?
  p= answer.body
  - if user_signed_in?
    p= link_to 'Edit', '', class: 'edit-answer-link btn btn-danger btn-xs', data: { answer_id: answer.id }, remote: true
    p
      = form_for answer, remote:true, html: { id: "edit-answer-#{answer.id}"} do |f|
        = f.label :body,  'Редактировать'
        = f.text_area :body
        = f.submit 'OK'

   

app/views/answers/create.js.erb
$('.answers').html('<%= j render @question.answers %>');
$('#answer_body').val('');

app/views/answers/update.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer-errors').html('<div class="alert alert-danger"><%= j message %></div>');
  <% end %>
<% else %>
  $('.answers').html('<%= j render @question.answers %>');
  $('.edit-answer-link').click(function(e) {
        e.preventDefault();
        $(this).hide();
        answer_id = $(this).data('answerId');
        $('form#edit-answer-' + answer_id).show();
  });
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Qna</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
<div class='container' %>
<%= yield %>
</div>
</body>
</html>

app/views/questions/_question.html.slim
h1= @question.title
p= @question.body
p Attachments:
ul
  - @question.attachments.each do |a|
    li= a.file.file.filename if  a.file.file
    li= link_to (image_tag a.file.url), a.file.url
.comments
  =form_for [@question, @question.comments.build], remote: true do |f|
    p
      = f.label :body, 'Comment'
      = f.text_area :body
    p
      = f.submit 'Post comment'
= link_to 'Delete', @question, method: :delete, data: {confirm: 'delete?'}

app/views/questions/edit.html.slim
.row
  .col-sm-12.col-md-6.col-md-offset-3.col-lg-6.col-lg-offset-3
    =form_for @question do |f|
      p
        = f.text_field :title, label: "Title"
        = f.text_area :body, label: "Text"
       
      p= f.submit 'исправить', class: "btn btn-primary"

app/views/questions/index.html.slim
 
- @questions.each do |question|
  h3 = link_to question.title, question_path(question)
- if can?(:create, Question)
  p= link_to 'Ask question', new_question_path
             

app/views/questions/new.html.slim
.row
  .col-sm-12.col-md-6.col-md-offset-3.col-lg-6.col-lg-offset-3
    =form_for @question do |f|
      p
        = f.text_field :title, label: "Title"
        = f.text_area :body, label: "Text"
       
      p Attachments:
      p 
        = f.fields_for :attachments do |a|
          = a.label :file
          = a.file_field :file
      p= f.submit 'Create', class: "btn btn-primary"

app/views/questions/show.html.slim
.row
  .col-md-6.col-md-offset-3
    .question
      .question-error
      .comment-errors
      = render @question
.row
  hr
  .answers data={ question_id: "#{@question.id}" }
    = render @question.answers
    .answer-errors
  = form_for [@question, @answer], remote:true do |f|
    = f.label :body,  'Ответ'
    = f.text_area :body
    = f.submit 'OK'

    /= render @question.answers
    / .row
    /   .col-md-4.col-md-offset-2
    /     = render 'comments/comments', resource: @question
    /     = render 'comments/form', resource: @question
    / .row
    /   hr
    /   .answers data={ question_id: "#{@question.id}" }
    /     = render @question.answers
    /     .answer-errors
    /   - if can?(:create, @answer)
    /     .user-auth data={ current_user: "#{ current_user.id }"}
    /     = bootstrap_nested_form_for [@question, @answer], remote: true do |f|
    /       = f.text_area :body, label: 'Answer'
    /       = f.fields_for :attachments, @answer.attachments.build do |a|
    /         = a.file_field :file, label: "File"
    /         = a.link_to_remove "Clear", class: "btn btn-xs btn-default float_left"
    /       = f.link_to_add 'Add more', :attachments, class: "btn btn-xs btn-default", style: "margin-left: 5px;"
    /       p
    /       = f.submit 'Create', class: "btn btn-primary"
    /   - else
    /     | Sign in or sign up to leave answers

    /   = subscribe_to "/questions/#{@question.id}"

app/views/questions/update.js.erb
<% if @question.errors.present? %>
  <% @question.errors.full_messages.each do |message| %>
    $('.question-errors').html('<div class="alert alert-danger"><%= j message %></div>');
  <% end %>
<% else %>
  $('.question').html('<%= j render @question %>');
  $('.edit-question-link').click(function(e) {
        e.preventDefault();
        $(this).hide();
        question_id = $(this).data('questionId');
        $('form#edit-question-' + question_id).show();
  });
<% end %>